version: 2.1
jobs: 
  build_app:
    docker: # Setup Environment
      - image: circleci/node:12.9.1-browsers
    working_directory: ~/circleci-demo-project
    parallelism: 2
    steps:
      - checkout # checkout the code in the project directory
      - run: echo "App Run"
  test_app:
    docker: # Setup Environment
      - image: circleci/node:12.9.1-browsers
    working_directory: ~/circleci-demo-project
    parallelism: 2
    steps:
      - checkout
      - run: echo "Test Steps completed"

workflows:
  version: 2
  build_and_test_app:
    jobs:
      - build_app
      - test_app
  