version: 2.1
jobs: 
  build:
    docker: # Setup Environment
      - image: circleci/node:12.9.1-browsers
    steps:
      - checkout # checkout the code in the project directory
      - run: echo "App Run"
